# Generated by Django 6.0.3 on 2026-04-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='role',
            field=models.CharField(choices=[('co_organiser', 'Co-organiser'), ('collaborator', 'Collaborator')], default='collaborator', max_length=20),
        ),
    ]
