# Generated by Django 6.0.3 on 2026-05-04 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_events', models.PositiveIntegerField(default=1)),
                ('max_sessions_per_event', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('co_organiser', 'Co-organiser'), ('collaborator', 'Collaborator')], default='collaborator', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subscriptionplan'),
        ),
    ]
