# Generated by Django 6.0.3 on 2026-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subscriptionplan_alter_eventmember_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('event', 'Event Guidance'), ('registration', 'Registration'), ('session', 'Session'), ('subscription', 'Subscription'), ('role', 'Role and Permission'), ('recommendation', 'Recommendation'), ('general', 'General')], default='general', max_length=30)),
                ('content', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
